Repository NexTach/Bstorm-server-V1, pull requests merged in 2024-11, with the labels that each got.

#52 관계 관련 로직 구현
  build.gradle
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignInServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignOutServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/AllMembersInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentProtectorMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentWardMembersInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/DeleteProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/ParticularMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PasswordChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PatchProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PhoneNumberChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/ResignServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/RoleChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/controller/RelationController.java
  src/main/java/com/nextech/server/v1/domain/relation/dto/request/DeleteRelationRequest.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/request/PostRelationRequest.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/response/RelationInqueryResponse.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/response/RelationInquiryListResponse.kt
  src/main/java/com/nextech/server/v1/domain/relation/service/AllDeleteRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/DeleteRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/GetRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/PostRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/AllDeleteRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/DeleteRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/GetRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/PostRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/exception/InvalidRoleException.java
  src/main/java/com/nextech/server/v1/global/exception/RelationAlreadyExistsException.java
  src/main/java/com/nextech/server/v1/global/members/entity/Members.kt
  src/main/java/com/nextech/server/v1/global/members/repository/MemberRepository.kt
  src/main/java/com/nextech/server/v1/global/members/service/MemberAuthService.kt
  src/main/java/com/nextech/server/v1/global/relation/entity/Relation.kt
  src/main/java/com/nextech/server/v1/global/relation/repository/RelationRepository.java
  src/main/java/com/nextech/server/v1/global/security/auth/AuthDetails.java
  src/main/java/com/nextech/server/v1/global/security/auth/AuthDetailsService.kt
  src/main/java/com/nextech/server/v1/global/security/jwt/service/JwtTokenService.java
  src/main/java/com/nextech/server/v1/global/swagger/SwaggerConfig.kt
Labels: bug, documentation, invent, refactor

#53 계정 간 관계 관련 로직 구현
  build.gradle
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignInServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignOutServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/AllMembersInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentProtectorMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/CurrentWardMembersInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/DeleteProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/ParticularMemberInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PasswordChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PatchProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PhoneNumberChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/ResignServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/RoleChangeServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/controller/RelationController.java
  src/main/java/com/nextech/server/v1/domain/relation/dto/request/DeleteRelationRequest.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/request/PostRelationRequest.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/response/RelationInqueryResponse.kt
  src/main/java/com/nextech/server/v1/domain/relation/dto/response/RelationInquiryListResponse.kt
  src/main/java/com/nextech/server/v1/domain/relation/service/AllDeleteRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/DeleteRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/GetRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/PostRelationService.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/AllDeleteRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/DeleteRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/GetRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/relation/service/impl/PostRelationServiceImpl.java
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/exception/InvalidRoleException.java
  src/main/java/com/nextech/server/v1/global/exception/RelationAlreadyExistsException.java
  src/main/java/com/nextech/server/v1/global/members/entity/Members.kt
  src/main/java/com/nextech/server/v1/global/members/repository/MemberRepository.kt
  src/main/java/com/nextech/server/v1/global/members/service/MemberAuthService.kt
  src/main/java/com/nextech/server/v1/global/relation/entity/Relation.kt
  src/main/java/com/nextech/server/v1/global/relation/repository/RelationRepository.java
  src/main/java/com/nextech/server/v1/global/security/auth/AuthDetails.java
  src/main/java/com/nextech/server/v1/global/security/auth/AuthDetailsService.kt
  src/main/java/com/nextech/server/v1/global/security/jwt/service/JwtTokenService.java
  src/main/java/com/nextech/server/v1/global/swagger/SwaggerConfig.kt
Labels: bug, documentation, invent, refactor

#55 CI 파이프라인 수정 및 Swagger 관련 기능 완전 삭제
  .github/workflows/gradle-build.yml
  README.md
  build.gradle
  src/main/java/com/nextech/server/v1/domain/auth/controller/AuthController.java
  src/main/java/com/nextech/server/v1/domain/auth/controller/TestMVCController.java
  src/main/java/com/nextech/server/v1/domain/members/controller/MembersController.java
  src/main/java/com/nextech/server/v1/domain/relation/controller/RelationController.java
  src/main/resources/static/css/SecurityTestStylesheet.css
  src/main/resources/static/js/SecurityTestScript.js
  src/main/resources/templates/SecurityTest.html
Labels: documentation, refactor

#56 불필요 CI 검사 삭제 및 Swagger 관련 기능 완전 삭제
  .github/workflows/gradle-build.yml
  README.md
  build.gradle
  src/main/java/com/nextech/server/v1/domain/auth/controller/AuthController.java
  src/main/java/com/nextech/server/v1/domain/auth/controller/TestMVCController.java
  src/main/java/com/nextech/server/v1/domain/members/controller/MembersController.java
  src/main/java/com/nextech/server/v1/domain/relation/controller/RelationController.java
  src/main/resources/static/css/SecurityTestStylesheet.css
  src/main/resources/static/js/SecurityTestScript.js
  src/main/resources/templates/SecurityTest.html
Labels: documentation, refactor

#57 Admin API 구현
  build.gradle
  src/main/java/com/nextech/server/v1/domain/admin/controller/AdminController.kt
  src/main/java/com/nextech/server/v1/domain/admin/dto/request/DeleteRefreshTokenRequest.kt
  src/main/java/com/nextech/server/v1/domain/admin/dto/response/LogResponse.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/AllDeleteRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/DeleteLogService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/DeleteRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/GetLogService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/GetRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/AllDeleteRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/DeleteLogServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/DeleteRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/GetLogServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/GetRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/auth/controller/AuthController.java
  src/main/java/com/nextech/server/v1/domain/auth/service/SignOutService.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignOutServiceImpl.java
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/exception/LogNotFoundException.java
  src/main/java/com/nextech/server/v1/global/exception/RefreshTokenDeletionFailedException.java
  src/main/java/com/nextech/server/v1/global/exception/RefreshTokenNotFoundException.java
  src/main/java/com/nextech/server/v1/global/redis/RedisConfig.kt
  src/main/java/com/nextech/server/v1/global/redis/RedisUtil.kt
  src/main/java/com/nextech/server/v1/global/security/config/SecurityConfig.kt
  src/main/java/com/nextech/server/v1/global/security/jwt/repository/RefreshTokenRepository.kt
Labels: invent, refactor

#58 Admin 전용 API 구현
  build.gradle
  src/main/java/com/nextech/server/v1/domain/admin/controller/AdminController.kt
  src/main/java/com/nextech/server/v1/domain/admin/dto/request/DeleteRefreshTokenRequest.kt
  src/main/java/com/nextech/server/v1/domain/admin/dto/response/LogResponse.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/AllDeleteRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/DeleteLogService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/DeleteRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/GetLogService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/GetRefreshTokenService.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/AllDeleteRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/DeleteLogServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/DeleteRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/GetLogServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/admin/service/impl/GetRefreshTokenServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/auth/controller/AuthController.java
  src/main/java/com/nextech/server/v1/domain/auth/service/SignOutService.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignOutServiceImpl.java
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/exception/LogNotFoundException.java
  src/main/java/com/nextech/server/v1/global/exception/RefreshTokenDeletionFailedException.java
  src/main/java/com/nextech/server/v1/global/exception/RefreshTokenNotFoundException.java
  src/main/java/com/nextech/server/v1/global/redis/RedisConfig.kt
  src/main/java/com/nextech/server/v1/global/redis/RedisUtil.kt
  src/main/java/com/nextech/server/v1/global/security/config/SecurityConfig.kt
  src/main/java/com/nextech/server/v1/global/security/jwt/repository/RefreshTokenRepository.kt
Labels: invent, refactor

#59 README.md 프로젝트 로고 삽입
  README.md
  image/Bstrom-logo.png
Labels: documentation

#60 README.md 프로젝트 메인 로고 삽입
  README.md
  image/Bstrom-logo.png
Labels: documentation

#61 AWS S3 관련 메서드 비동기 처리 적용
  src/main/java/com/nextech/server/v1/BstormServerV1Application.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/DeleteProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PatchProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/global/aws/service/FileDeleteService.java
  src/main/java/com/nextech/server/v1/global/aws/service/FileUploadService.java
Labels: invent, refactor

#62 AWS S3 관련 메서드 비동기화
  src/main/java/com/nextech/server/v1/BstormServerV1Application.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/DeleteProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/service/impl/PatchProfilePictureServiceImpl.java
  src/main/java/com/nextech/server/v1/global/aws/service/FileDeleteService.java
  src/main/java/com/nextech/server/v1/global/aws/service/FileUploadService.java
Labels: invent, refactor

#69 비밀번호 불일치 시 HTTP 상태코드 반환값 오류 및 로그인,토큰 재발급 시 필드 이름 컨벤션 불일치 문제 해결
  src/main/java/com/nextech/server/v1/domain/auth/dto/response/ReissueResponse.kt
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/ReissueServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/controller/MembersController.java
  src/main/java/com/nextech/server/v1/global/dto/response/TokenResponse.kt
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
Labels: bug, refactor

#70 Mission 기능 일부 완성 및 HTTP 상태코드,컨벤션 불일치 문제 해결
  logs/application.log/spring.log
  src/main/java/com/nextech/server/v1/domain/auth/dto/response/ReissueResponse.kt
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/ReissueServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/members/controller/MembersController.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/enums/Status.java
  src/main/java/com/nextech/server/v1/domain/mission/entity/Mission.java
  src/main/java/com/nextech/server/v1/global/dto/response/TokenResponse.kt
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/members/entity/Members.kt
Labels: bug, invent, refactor

#66 Mission 관련 API 구현
  logs/application.log/spring.log
  logs/application.log/spring.log.2024-11-24.0.gz
  logs/application.log/spring.log.2024-11-25.0.gz
  src/main/java/com/nextech/server/v1/domain/members/repository/MembersRepository.java
  src/main/java/com/nextech/server/v1/domain/mission/controller/MissionController.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/request/MissionRequestDto.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/request/MissionStatusUpdateRequestDto.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/request/MissionUpdateRequestDto.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/response/ErrorResponseDto.java
  src/main/java/com/nextech/server/v1/domain/mission/dto/response/MissionResponseDto.java
  src/main/java/com/nextech/server/v1/domain/mission/entity/Mission.java
  src/main/java/com/nextech/server/v1/domain/mission/repository/MissionRepository.java
  src/main/java/com/nextech/server/v1/domain/mission/service/AllMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/CustomMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/ExpiredMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/FailedMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/MissionCreateService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/MissionDeleteService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/MissionStatusUpdateService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/MissionUpdateService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/ParticularMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/ProgressMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/SuccessfulMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/SystemMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/UserMissionInquiryService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/AllMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/CustomMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/ExpiredMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/FailedMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/MissionCreateServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/MissionDeleteServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/MissionStatusUpdateServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/MissionUpdateServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/ParticularMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/ProgressMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/SuccessfulMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/SystemMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/UserMissionInquiryServiceImpl.java
  src/main/java/com/nextech/server/v1/global/members/entity/Members.kt
  src/main/java/com/nextech/server/v1/global/security/config/SecurityConfig.kt
Labels: invent

#71 Mission 체크리스트 관련 로직 추가
  src/main/java/com/nextech/server/v1/domain/auth/service/impl/SignUpServiceImpl.java
  src/main/java/com/nextech/server/v1/domain/mission/controller/MissionController.java
  src/main/java/com/nextech/server/v1/domain/mission/entity/MissionList.kt
  src/main/java/com/nextech/server/v1/domain/mission/repository/MissionListRepository.kt
  src/main/java/com/nextech/server/v1/domain/mission/service/GetMissionListService.kt
  src/main/java/com/nextech/server/v1/domain/mission/service/MissionStatusUpdateService.java
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/GetMissionListServiceImpl.kt
  src/main/java/com/nextech/server/v1/domain/mission/service/impl/MissionStatusUpdateServiceImpl.java
  src/main/java/com/nextech/server/v1/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nextech/server/v1/global/exception/MissionListNotFoundException.java
Labels: invent, refactor
